defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = [""]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[acme]
caServer = "https://acme-v02.api.letsencrypt.org/directory"
email = ""
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[acme.tlsChallenge]
